### ISSUE TITLE
Search priority for files

### ISSUE THREAD

**Issue by shuhrat** [ehmicky/preferred-node-version#6]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

Given `.nvmrc` and `package.json` files. Now there is no guarantee that package first will try to check `.nvmrc` or `package.json`. Priority is not clearly defined and highly depends on `Object.keys` implementation.

### Describe the solution you'd like

It would be great to define order and describe it in README. I think [here](https://github.com/ehmicky/preferred-node-version/blob/main/src/load.js#L52) in `NODE_VERSION_FILES` could return ordered list of files.

### Pull request (optional)

- [X] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @shuhrat,

Thanks for reaching out!

`Object.keys()` order is well-defined in JavaScript ([link to spec](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-ordinaryownpropertykeys) and to [blog post](https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/) about it). So the files priority follows the keys order in:

https://github.com/ehmicky/preferred-node-version/blob/e3966ecfe517ea290a9037b4723f8e640270b29e/src/load.js#L38-L51

For example, `.nvmrc` should always have the priority over `package.json`.  

I have created a new test for that behavior. I have also clarified the `README` to explicitly document the expected order of operations. Please let me know what you think!

**Comment by ehmicky** [comment]
@all-contributors Please add @shuhrat for ideas and question.

**Comment by shuhrat** [comment]
Now documentation looks much better. Thank you!
